### ISSUE TITLE
Does it work with the freeplan?

### ISSUE THREAD

**Issue by BobWs** [tsjensen/protonmail-bridge-docker#3]
Hi I was wondering if this will work with the freeplan or is it just for the paid version?
TIA

**Comment by tsjensen** [comment]
protonmail-bridge-docker requires that you already have valid credentials for the ProtonMail Bridge. According to the [ProtonMail Bridge website](https://protonmail.com/bridge/) this means you must be a "paying user" of ProtonMail, I'm afraid.

**Comment by BobWs** [comment]
Thanks for sharing! I only have the freeplan so it isn’t for me😌
